[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.30'
bytecode_hash = "none"
cbor_metadata = false
via_ir = true
optimizer = true
optimizer_runs = 200
evm_version = 'shanghai'
extra_output = ["storageLayout"]

[invariant]
runs = 256
depth = 50
fail_on_revert = false

[rpc_endpoints]
rpc_url = "${RPC_URL}"
plume_mainnet = "https://rpc.plume.org"
plume_testnet = "https://testnet-rpc.plume.org"

[etherscan]
plume_mainnet = { key = "", chain = 98866, url = "https://explorer.plume.org/api/" }
plume_testnet = { key = "", chain = 98867, url = "https://testnet-explorer.plume.org/api/" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
